apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: databases

requires:
  - configs: ["postgres"]
    path: postgres
    activeProfiles: &profiles
      - name: minikube
        activatedBy: [minikube]

  - configs: ["redis"]
    path: redis
    activeProfiles: *profiles

  - configs: ["mongodb"]
    path: mongodb
    activeProfiles: *profiles

  # - configs: ["duckdb"]
  #   path: duckdb
  #   activeProfiles: *profiles
