apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: product-service

requires:
  - configs: ["mongodb"]
    path: ../../infrastructure/databases/mongodb
    activeProfiles: &profiles
      - name: minikube
        activatedBy: [minikube]

  - configs: ["redis"]
    path: ../../infrastructure/databases/redis
    activeProfiles: *profiles

profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: product-service
          context: .
          docker:
            dockerfile: Dockerfile
            target: development
      local:
        useBuildkit: true
        concurrency: 0
    deploy:
      kubectl: {}
    manifests:
      rawYaml:
        - ./k8s/*.yml
    portForward:
      - resourceType: service
        resourceName: product-service
        port: 8080
        localPort: 8380
