apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: cloud-native-samples

requires:

  # - configs: ["infrastructure"]
  #   path: infrastructure
  #   activeProfiles: &profiles
  #     - name: local
  #       activatedBy: [local]

  - configs: ["order-service"]
    path: services/order-service
    activeProfiles: &profiles
      - name: local
        activatedBy: [local]

  # - configs: ["product-service"]
  #   path: services/product-service
  #   activeProfiles: *profiles

  # - configs: ["order-service"]
  #   path: services/order-service
  #   activeProfiles: *profiles

  # - configs: ["user-service"]
  #   path: services/user-service
  #   activeProfiles: *profiles
