apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: security

requires:
  - configs: ["keycloak"]
    path: keycloak
    activeProfiles: &profiles
      - name: minikube
        activatedBy: [minikube]
