apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: postgres

profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
    deploy:
      helm:
        releases:
          - name: postgres
            repo: https://charts.bitnami.com/bitnami
            remoteChart: postgresql
            version: 12.6.0
            setValues:
              image.tag: 13.6.0-debian-10-r89
              image.debug: true
              primary.extraEnvVars:
                - name: POSTGRESQL_WAL_LEVEL
                  value: logical
              global.postgresql.auth.postgresPassword: "password"
              primary.initdb.scripts.init\.sql: "
                CREATE DATABASE keycloak;
                CREATE DATABASE demo;"
            namespace: default
    portForward:
      - resourceType: service
        resourceName: postgres-postgresql
        port: 5432
        localPort: 5432
