apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: postgres

profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
    deploy:
      kubectl: {}
    manifests:
      rawYaml:
        - ./k8s/*.yml
    portForward:
      - resourceType: service
        resourceName: postgres
        port: 5432
        localPort: 5432
    #   helm:
    #     releases:
    #       - name: postgres
    #         repo: https://charts.bitnami.com/bitnami
    #         remoteChart: postgresql
    #         version: 12.6.0
    #         setValues:
    #           image.tag: 13.6.0-debian-10-r89
    #           image.debug: true
    #           architecture: standalone
    #           primary.persistence.size: 5Gi
    #           replica.persistence.size: 5Gi
    #           global.postgresql.auth.postgresUser: "postgres"
    #           global.postgresql.auth.database: "postgres"
    #           global.postgresql.auth.password: "password"
    #           primary.extraEnvVars:
    #             - name: POSTGRESQL_WAL_LEVEL
    #               value: logical
    #           #global.postgresql.auth.postgresPassword: "password"
    #           primary.initdb.scripts.init\.sql: "
    #             CREATE DATABASE keycloak;
    #             CREATE DATABASE demo;"
    #         namespace: default
    # portForward:
    #   - resourceType: service
    #     resourceName: postgres-postgresql
    #     port: 5432
    #     localPort: 5432
