apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: krakend

profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: krakend
          context: .
          docker:
            dockerfile: Dockerfile
            target: development
      local:
        useBuildkit: true
        concurrency: 0
    deploy:
      kubectl: {}
    manifests:
      rawYaml:
        - ./k8s/*.yml
    portForward:
      - resourceType: service
        resourceName: krakend
        port: 8080
        localPort: 8180
