apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: services

requires:
  - configs: ["order-service"]
    path: order-service
    activeProfiles: &profiles
      - name: minikube
        activatedBy: [minikube]
      - name: cloud
        activatedBy: [gcp]

profiles:
  - name: minikube
    build:
      local:
        concurrency: 0
        useBuildkit: true
    activation:
      - kubeContext: minikube
