apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: redis

profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
    deploy:
      helm:
        releases:
          - name: redis
            repo: https://charts.bitnami.com/bitnami
            remoteChart: redis
            version: 18.7.0
            setValues:
              architecture: standalone
              auth.enabled: false
    portForward:
      - resourceType: service
        resourceName: redis-master
        port: 6379
        localPort: 6379
