apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: mongodb

profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
    deploy:
      helm:
        releases:
          - name: mongodb
            repo: https://charts.bitnami.com/bitnami
            remoteChart: mongodb
            version: 12.1.16
            setValues:
              image.tag: 4.4-debian-10
              replicaCount: 1
              arbiter.enabled: false
              architecture: replicaset
              useStatefulSet: true
              livenessProbe.enabled: false
              readinessProbe.enabled: false
              persistence:
                size: 5Gi
              auth:
                enabled: false
    portForward:
      - resourceType: service
        resourceName: mongodb-headless
        port: 27017
        localPort: 27017
