---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"  # Maximum memory allowed
            cpu: "200m"       # Maximum CPU allowed (200 milliCPU)
          requests:
            memory: "128Mi"  # Initial memory request
            cpu: "100m"       # Initial CPU request
        # livenessProbe:
        #   httpGet:
        #     path: /                # The path to check for the liveness probe
        #     port: 80               # The port to check on
        #   initialDelaySeconds: 15  # Wait this many seconds before starting the probe
        #   periodSeconds: 10        # Check the probe every 10 seconds
        # readinessProbe:
        #   httpGet:
        #     path: /                # The path to check for the readiness probe
        #     port: 80               # The port to check on
        #   initialDelaySeconds: 5   # Wait this many seconds before starting the probe
        #   periodSeconds: 5         # Check the probe every 5 seconds

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
