apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: api-gateway

requires:
  - configs: ["krakend"]
    path: krakend
    activeProfiles: &profiles
      - name: minikube
        activatedBy: [minikube]

  # - configs: ["kong"]
  #   path: kong
  #   activeProfiles: *profiles
