---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service
        ports:
          - containerPort: 3000
        env:
        - name: NODE_ENV
          value: development
        - name: LOG_LEVEL
          value: info
        - name: CORS_ORIGIN
          value: "*"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: order-service-secret
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: order-service-secret
              key: jwt-secret
        - name: JWT_EXPIRES_IN
          value: 1d
        resources:
          limits:
            memory: "256Mi"  # Maximum memory allowed
            cpu: "200m"       # Maximum CPU allowed (200 milliCPU)
          requests:
            memory: "128Mi"  # Initial memory request
            cpu: "100m"       # Initial CPU request
        livenessProbe:
          httpGet:
            path: /health          # The path to check for the liveness probe
            port: 3000             # The port to check on
          initialDelaySeconds: 30  # Wait this many seconds before starting the probe
          periodSeconds: 10        # Check the probe every 10 seconds
        # readinessProbe:
        #   httpGet:
        #     path: /                # The path to check for the readiness probe
        #     port: 3000             # The port to check on
        #   initialDelaySeconds: 10  # Wait this many seconds before starting the probe
        #   periodSeconds: 5         # Check the probe every 5 seconds
      #   volumeMounts:
      #   - name: config-volume
      #     mountPath: /opt/app/config
      # volumes:
      # - name: config-volume
      #   configMap:
      #     name: order-service-config
