apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL21vbmdvZGIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9vcmRlcg== # base64 encoded "mongodb://mongodb.default.svc.cluster.local:27017/order"
  jwt-secret: ZGV2X3N1cGVyX3NlY3JldA== # base64 encoded "dev_super_secret"
