apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvb3JkZXI= # base64 encoded "mongodb://mongodb:27017/order"
  jwt-secret: ZGV2X3N1cGVyX3NlY3JldA== # base64 encoded "dev_super_secret"
