apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: keycloak

requires:
  - configs: ["postgres"]
    path: ../../databases/postgres
    activeProfiles: &profiles
      - name: minikube
        activatedBy: [minikube]

profiles:
  - name: minikube
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: keycloak
          context: .
          docker:
            dockerfile: Dockerfile
            target: development
      local:
        useBuildkit: true
        concurrency: 0
    deploy: &deploy
      kubectl: {}
    manifests: &manifests
      rawYaml:
        - ./k8s/*.yml
    portForward: &portForward
      - resourceType: service
        resourceName: keycloak
        port: 8080
        localPort: 8280
    activation:
      - kubeContext: minikube
