---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: wait-postgres
          image: postgres:13
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h postgres-postgresql -p 5432; do echo waiting for database; sleep 2; done;",
            ]
      containers:
      - name: keycloak
        image: keycloak
        #args: ["start-dev"]
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        env:
        # Deprecated
        # - name: KEYCLOAK_ADMIN
        #   valueFrom:
        #     secretKeyRef:
        #       name: keycloak-admin-secret
        #       key: admin-user
        # - name: KEYCLOAK_ADMIN_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: keycloak-admin-secret
        #       key: admin-password
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-secret
              key: admin-user
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-secret
              key: admin-password
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/keycloak"
        - name: KC_DB_USERNAME
          value: "postgres"
          # valueFrom:
          #   secretKeyRef:
          #     name: keycloak-db-secret
          #     key: username
        - name: KC_DB_PASSWORD
          value: "password"
          # valueFrom:
          #   secretKeyRef:
          #     name: keycloak-db-secret
          #     key: password
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        # - name: KC_HOSTNAME_STRICT_BACKCHANNEL
        #   value: "false"
        - name: KC_HTTP_RELATIVE_PATH
          value: "/auth"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 30
