---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: wait-postgres
          image: postgres:13
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h postgres-postgresql -p 5432; do echo waiting for database; sleep 2; done;",
            ]
      containers:
        - name: keycloak
          image: keycloak
          #args: ["--import-realm"]
          env:
            # See https://www.keycloak.org/server/all-config
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
            # DATABASE
            - name: KC_DB
              value: "postgres"
            # - name: KC_DB_URL
            #   value: "jdbc:postgresql://postgres-postgresql.default.svc.cluster.local/keycloak"
            - name: KC_DB_URL_HOST
              value: "postgres-postgresql"
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: "keycloak"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_PASSWORD
              value: "keycloak"
            - name: KC_HTTP_PORT
              value: "9000"
            # - name: KC_HOSTNAME_STRICT
            #   value: "false"
            # - name: KC_HOSTNAME_STRICT_BACKCHANNEL
            #   value: "false"
            # Enables the HTTP listener
            - name: KC_HTTP_ENABLED
              value: "true"
            # By default, the new Quarkus distribution removes /auth from the context-path.
            # The following parameter will re-introduce the /auth
            - name: KC_HTTP_RELATIVE_PATH
              value: "/auth"
          # ports:
          #   - name: http
          #     containerPort: 9000
          # readinessProbe:
          #   httpGet:
          #     # If the KC_HTTP_RELATIVE_PATH is disable, remove the /auth path from /auth/realms/master
          #     path: /auth/realms/master
          #     port: 9000
