apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
data:
  admin-user: YWRtaW4= # base64 encoded "admin"
  admin-password: YWRtaW4= # base64 encoded "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
data:
  username: a2V5Y2xvYWs= # base64 encoded "keycloak"
  password: a2V5Y2xvYWs= # base64 encoded "keycloak"
