---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      containers:
      - name: streaming-service
        image: ntdtfr/streaming-service:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"  # Maximum memory allowed
            cpu: "200m"       # Maximum CPU allowed (200 milliCPU)
          requests:
            memory: "128Mi"  # Initial memory request
            cpu: "100m"       # Initial CPU request
        # livenessProbe:
        #   httpGet:
        #     path: /                # The path to check for the liveness probe
        #     port: 80               # The port to check on
        #   initialDelaySeconds: 15  # Wait this many seconds before starting the probe
        #   periodSeconds: 10        # Check the probe every 10 seconds
        # readinessProbe:
        #   httpGet:
        #     path: /                # The path to check for the readiness probe
        #     port: 80               # The port to check on
        #   initialDelaySeconds: 5   # Wait this many seconds before starting the probe
        #   periodSeconds: 5         # Check the probe every 5 seconds

---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
spec:
  selector:
    app:
    app: streaming-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
