
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    #container_name: order-service
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/order
    volumes:
      - ./src:/opt/app/src
      - ./docs:/opt/app/docs
    depends_on:
      - mongo
    networks:
      - order-service-network

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - order-service-network

networks:
  order-service-network:
    driver: bridge

volumes:
  mongo-data:
