apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: order-service

requires:
  - configs: ["mongodb"]
    git:
      repo: https://github.com/ntdtfr/tools.git
      path: databases/mongodb/skaffold.yaml
      ref: main
      sync: true
    activeProfiles: &profiles
      - name: minikube
        activatedBy: [minikube]

profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
    build:
      # platforms:
      #   - "linux/amd64"
      #   - "linux/arm64"
      tagPolicy:
        sha256: {}
      artifacts:
        - image: order-service
          context: .
          docker:
            dockerfile: Dockerfile
            target: production
            buildArgs:
              NODE_VERSION: "22"
              GITHUB_EMAIL: "{{ .GITHUB_EMAIL }}"
              GITHUB_USER: "{{ .GITHUB_USER }}"
            # cacheFrom:
            #   - order-service
          # sync:
          #   infer: ["**/*"]
          #   # manual:
          #   # - src: "src/**/*"
          #   #   dest: "/opt/app/"
      local:
        useBuildkit: true
        concurrency: 0
    # test:
    #   - image: order-service
    #     command: [ "npm", "run", "test" ]
    #     args: [ "--", "--watchAll=false" ]
    deploy:
      kubectl: {}
    manifests:
      rawYaml:
        - ./k8s/*.yml
    portForward:
      - resourceType: service
        resourceName: order-service
        port: 3000
        localPort: 8002
