apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: order-service

profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: order-service
          context: .
          docker:
            dockerfile: Dockerfile
            target: development
          # sync:
          #   infer: ["**/*"]
          #   # manual:
          #   # - src: "src/**/*"
          #   #   dest: "/opt/app/"
      local:
        useBuildkit: true
        concurrency: 0
    deploy:
      kubectl: {}
    manifests:
      rawYaml:
        - ./k8s/*.yml
    portForward:
      - resourceType: service
        resourceName: order-service
        port: 3000
        localPort: 8480
