version: '3'
services:
  streaming-service:
    image: streaming-service:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: streaming-service
    restart: always
    # volumes:
    #   - ./videos:/opt/streaming-service/videos
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
