apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
data:
  krakend.json: |
    {
      "version": 3,
      "endpoints": [
        {
          "endpoint": "/api/v1/orders",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/orders",
              "host": ["http://order-service:3000"]
            }
          ]
        }
      ]
    }
