name: Lint title

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  validate-title:
    name: Validate Pull Request Title
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
