name: Order Service CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    tags: [ v* ]
    # paths-ignore:
    #   - '**.md'
    paths:
      - services/order-service/src/**
      - services/order-service/Dockerfile
      - .github/workflows/order-service-ci.yml
  pull_request:
    branches: [ master ]
    # paths-ignore:
    #   - '**.md'
    paths:
      - services/order-service/src/**
      - services/order-service/Dockerfile
      - .github/workflows/order-service-ci.yml

# Environment variables available to all jobs and steps in this workflow
env:
  SOURCE_DIR: services/order-service
  NODE_VERSION: 22
  DOCKER_REGISTRY: docker.io  # ghcr.io
  DOCKER_IMAGE_NAME: ntdtfr/order-service
  DOCKER_TARGET: production

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - name: Change working directory
      run: |
        pwd
        cd ${{ env.SOURCE_DIR }}
        pwd

    - name: Install npm version 11.3.0 and babel CLI
      run: |
        npm install -g npm@11.3.0
        npm install -g babel-cli

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Build application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 1

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v3

    - name: Run dependency vulnerability check
      run: npm audit --production

    - name: Run SAST scan
      uses: github/codeql-action/analyze@v2
      with:
        languages: javascript

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [build-and-test, security-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: services/order-service/Dockerfile
        target: production
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE_NAME }}:latest
          ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to production
      run: |
        # Replace with your deployment script or actions
        echo "Deploying to production environment"
        # Add your deployment steps here
